# mk-ca-bundle
# Autogenerated from man page /usr/share/man/man1/mk-ca-bundle.1.gz
complete -c mk-ca-bundle -s b -d 'backup an existing version of outputfilename'
complete -c mk-ca-bundle -s d -d 'specify which Mozilla tree to pull certdata. txt from (or a custom URL)'
complete -c mk-ca-bundle -s f -d 'force rebuild even if certdata. txt is current (Added in version 1. 17)'
complete -c mk-ca-bundle -s i -d 'print version info about used modules'
complete -c mk-ca-bundle -s k -d 'Allow insecure data transfer.  By default (since 1'
complete -c mk-ca-bundle -s l -d 'print license info about certdata. txt'
complete -c mk-ca-bundle -s m -d '(Added in 1. 26) Include meta data comments in the output'
complete -c mk-ca-bundle -s n -d 'no download of certdata. txt (to use existing)'
complete -c mk-ca-bundle -s p -d 'list of Mozilla trust purposes and levels for certificates to include in outp…'
complete -c mk-ca-bundle -s q -d 'be really quiet (no progress output at all)'
complete -c mk-ca-bundle -s t -d 'include plain text listing of certificates'
complete -c mk-ca-bundle -s s -d 'comma separated list of signature algorithms with which to hash/fingerprint e…'
complete -c mk-ca-bundle -s u -d 'unlink (remove) certdata. txt after processing'
complete -c mk-ca-bundle -s v -d 'be verbose and print out processed certificate authorities EXIT STATUS Return…'

