# swaylock
# Autogenerated from man page /usr/share/man/man1/swaylock.1.gz
complete -c swaylock -s C -l config -d 'The config file to use.  By default, the following paths are checked:'
complete -c swaylock -s d -l debug -d 'Enable debugging output'
complete -c swaylock -s e -l ignore-empty-password -d 'When an empty password is provided, do not validate it'
complete -c swaylock -s F -l show-failed-attempts -d 'Show current count of failed authentication attempts'
complete -c swaylock -s f -l daemonize -d 'Detach from the controlling terminal after locking'
complete -c swaylock -l fade-in -d 'Fade in the lock screen'
complete -c swaylock -l submit-on-touch -d 'Submit password in response to a touch event'
complete -c swaylock -l grace -d 'Only require a password after some grace period'
complete -c swaylock -l grace-no-mouse -d 'With --grace, don\'t unlock in response to a mouse event'
complete -c swaylock -l grace-no-touch -d 'With --grace, don\'t unlock in response to a touch event'
complete -c swaylock -s h -l help -d 'Show help message and quit'
complete -c swaylock -s v -l version -d 'Show the version number and quit'

