# swww-init
# Autogenerated from man page /usr/share/man/man1/swww-init.1.gz
complete -c swww-init -l no-daemon -d 'Don\'t fork the daemon.  This will keep it running in the current terminal'
complete -c swww-init -l no-cache -d 'Don\'t load the cache during initialization (it still loads on monitor (re)con…'
complete -c swww-init -s h -l help -d 'Print help (see a summary with \'-h\')'

