# wlsunset
# Autogenerated from man page /usr/share/man/man1/wlsunset.1.gz
complete -c wlsunset -s h -d 'show this help message'
complete -c wlsunset -s T -d 'set high temperature (default: 6500)'
complete -c wlsunset -s t -d 'set low temperature (default: 4000)'
complete -c wlsunset -s l -d 'set latitude (e. g.  39. 9)'
complete -c wlsunset -s L -d 'set longitude (e. g.  116. 3)'
complete -c wlsunset -s S -d 'Manual time for sunrise as HH:MM (e. g.  06:30)'
complete -c wlsunset -s s -d 'Manual time for sunset as HH:MM (e. g.  18:30)'
complete -c wlsunset -s d -d 'Manual animation time in seconds (e. g.  1800)'
complete -c wlsunset -s g -d 'set gamma (default: 1. 0)'

